#  Tema 2 

## Termen de predare: 25 octombrie 2023, ora 20:00.
Timp de lucru: 1 săptămână

## Precizări

1. Se vor folosi **type annotations** pentru variabile, parametri tuturor funcțiilor, tipuri de retur. Se vor folosi **docstrings** pentru toate funcțiile. Neîndeplinirea acestei cerințe duce la **înjumătățirea punctajului** pentru exercițiul în cauză. 
1. Înainte de a trimite tema, verificați acoperirea cerințelor. 
1. Notebook-ul trebuie să ruleze complet, de sus în jos ``(kernel-> Run All)``. Orice execție oprită duce la punctarea temei până în punctul respectiv.


## Conținut

1. Exercitii cu functii
1. Exercitii cu NumPy

In [2]:
import math
import numpy as np

## Execiții cu funcții:


 (1p) 1.Să se scrie o funcție care calculează suma cuburilor primelor n numere, n dat ca input, folosind List comprehension.

In [81]:
def sum_of_first_n_cubes(n:int)->int :
    """
    This function returns the sum of the cubes of the first 'n' natural numbers, n being given as input.
    Function returns an int value.
    """
    return sum([number**3 for number in range(0,n)])

n=input("n=")
print(sum_of_first_n_cubes(int(n)))

100


(1p) 2. Scrieți o funcție care duplicatele din secvențe.

Exemplu: ['a','a','a','a','b','c','c','a','a','d','e','e','e','e'] => ['a','b','c','a','d','e']

In [5]:
def remove_duplicates(sequence:list)->list :
    """
    This function removes the duplicate values in a list.
    It returns a list.
    """
    return [sequence[i] for i in range(len(sequence)) if i==0 or sequence[i] != sequence[i-1]]

print(remove_duplicates(['a','a','a','a','b','c','c','a','a','d','e','e','e','e']))

['a', 'b', 'c', 'a', 'd', 'e']


(1p) 3. Definiți o funcție care primește ca parametru o propoziție (string sau listă). Să se returneze un tuplu ce indică numărul de cuvinte cu diftongi , numărul de cuvinte cu triftongi și numărul de cifre din parametrul primit. Verificați dacă suma celor 3 valori formează un număr palindrom.

Penru ușurința exercițiului, vom considera:

Diftong = 2 vocale alăturate

Triftong = 3 vocale alăturate

În realitate ([link](https://www.gimnaziu.info/diftongul-triftongul-hiatul))
Diftong = grup de sunete format din 1 vocală și o semivocală, pronunțate în aceeași silabă.

Triftong = grup de sunete format din 1 vocală și 2 semivocale, pronunțate în aceeași silabă


exemplu:
diftongi: iar-nă; broas-că; deal; soa-re; pia-tră, mai; grâu; ca-doum câi-ne; vrei.

triftongi:
leoar-că, pleoa-pă, ve-deau, iau, zme-oaica, in-do-iau, miei, piei

In [10]:
def check_palindrom(number:int)->bool :
    """
    This function checks if a number is a palindrome.
    It returns a boolean value.
    """
    return int(str(number)[::-1]) == number

def dift_trift_num_digits(sentence:str)->tuple :
    """
    This function processes a sentence and returns the number of words that contain a diftong, a triftong and the number of digits.
    It returns a tuple with the 3 values.
    """
    sentence=sentence.split()
    vowels='aeiouAEIOU'
    num_dift:int = len([word for word in sentence for i in range(len(word) - 1) if word[i] in vowels and word[i + 1] in vowels])
    num_trift:int = len([word for word in sentence if len(word) >= 3 for i in range(len(word) - 2) if word[i] in vowels and word[i + 1] in vowels and word[i + 2] in vowels])
    num_digits:int = sum([len(str(word)) for word in sentence if word.isnumeric()])
    return (num_dift-2*num_trift,num_trift,num_digits)
    
#dift: 3, trift: 1, cifre: 9
sentence="Ana are 27 borcane de miere si 3 piersici. Ea este femeie. 245 53 0 "
print(dift_trift_num_digits(sentence))
print("Tuple is palindrome:",check_palindrom(sum((dift_trift_num_digits(sentence)))))



(3, 1, 9)
Tuple is palindrome: False


(1p) 4. Să se scrie o funcție recursivă `suma_cifre_impare` care calculează suma cifrelor impare ale unui număr. Într-o altă funcție `black_hole` se apelează în mod repetat `suma_cifre_impare` pe numărul rezultat, până când se atinge un număr maxim de iterații (implicit 10) sau se ajunge la numărul 1000. Puteți crea alte  functii auxiliare. 

In [84]:
def suma_cifre_impare(number:int)->int :
    """
    This recursive function returns the sum of the odd digits of a number given as input.
    It returns an integer value.
    """
    if number < 10 and number%2 != 0 :
        return number
    if number%10%2 != 0 :
        return number%10+suma_cifre_impare(number//10)
    else : return suma_cifre_impare(number//10)

def black_hole(number:int)->int :
    """
    This function calls for the function suma_cifre_impare on a number given as input 10 times (max_iterations) or until the number value reaches 1000.
    It returns an integer value.
    """
    no_iterations = 0
    max_iterations = 10
    while number != 1000 and no_iterations < 10 :
        number=suma_cifre_impare(number)
        no_iterations+=1
    if(no_iterations == max_iterations) :
        return no_iterations
    else : return number

number=input("number=")
print(suma_cifre_impare(int(number)))
print(black_hole(int(number)))

5
10


## Probleme NumPy

(1 p) 1. Se dă un vector NumPy. Să se determine lista elementelor pătrate perfecte. Formați o matrice pătratică de dimensiune  `len(v)/2` care să conțină elementele pătrate perfecte din vector.
Completați pozițiile din matrice rămase libere cu cmmmc al rădăcinilor elementelor pătrate perfecte .  

In [85]:
def cmmmc(number1:int, number2:int)->int:
    """
    This function find the lowest common multiple of 2 numbers given as input.
    It returns an integer value.
    """
    if number1 > number2  :
        maxim:int=number1
    else : maxim:int=number2
    for i in range(maxim,number1*number2+1) :
        if i%number1 == 0 and i%number2==0 :
            return i
        
def cmmmc_list(vector:list)-> int:
    """
    This function find the lowest common multiple of all the numbers in a list given as an input.
    It returns an integer value.
    """
    lowest_multiple:int=cmmmc(vector[0],vector[1])
    for i in range(2,len(vector)) :
        lowest_multiple:int=cmmmc(lowest_multiple,vector[i])
    return lowest_multiple

vector = np.array([1,2,3,4,9,11,13,16,25,36,50,102,49])
perfect_squares:list = [number for number in vector if math.sqrt(number) == int(math.sqrt(number))]
roots:list=[int(math.sqrt(number)) for number in perfect_squares]
lowest_multiple_roots:int = cmmmc_list(roots)

dim_matrix = len(perfect_squares)//2
matrix=np.zeros((dim_matrix,dim_matrix), dtype=int)

for i in range(dim_matrix):
    for j in range(dim_matrix):
        if perfect_squares:
            matrix[i, j] = perfect_squares.pop(0)

for i in range(dim_matrix) :
    for j in range(dim_matrix) :
        if matrix[i,j]==0 :
            matrix[i,j]=lowest_multiple_roots  

print(matrix)


[[  1   4   9]
 [ 16  25  36]
 [ 49 420 420]]


(1.5 p) 2. Se dau punctele de forma $A_n(5n, 8n+1)$. 

a) Calculați distanța euclidiană dintre perechile de puncte $A_{n-1}$, $A_n$, n=1...6. <br>
$$
 d\left( p,q\right)   = \sqrt {\sum _{i=1}^{n}  \left( q_{i}-p_{i}\right)^2 } 
$$

b) Verificați dacă punctele $A_6, A_2, A_8$ sunt coliniare. <br>
c) Aria triunghiului determinat de punctele $A_3, A_4, A_5$
    
   **Indicație**: Puteți folosi noțiunea de determinant.

$$\displaystyle \det(M)={\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix}}=a_{11}a_{22}a_{33}+a_{12}a_{23}a_{31}+a_{13}a_{21}a_{32}-a_{31}a_{22}a_{13}-a_{32}a_{23}a_{11}-a_{33}a_{21}a_{12}.$$

$A(x_A, y_A), B(x_B, Y_B) , C(x_C,y_c)$ 

sunt coliniare, atunci: $$\begin{vmatrix}x_ A& y_A & 1\\
x_B & y_B & 1\\
x_C & y_C & 1
\end{vmatrix}=0$$


Python: points: np.array $\implies$ `np.linalg.det(points)` Mai multe informații, la [link](https://www.geeksforgeeks.org/numpy-linalg-det-method-in-python/)




In [8]:
def euclidean_distance(point_A:tuple, point_B:tuple)->float:
    """
    This function recieves as input 2 points (tuple of 2 coordonates each).
    It returns a float value representing the euclidian distance between the two points.
    The euclidian distance is calculated via the following formula:

        euclidean_distance = sqrt((point_B[1] - point_A[1])**2 + (point_B[0] - point_A[0])**2)
    """
    return math.sqrt((point_B[1]-point_A[1])**2 + (point_B[0]-point_A[0])**2)

############################################################################################

print("A)")
#n=input("n=")
for index in range(1,6) :
    point_A:tuple=(5*index,8*index+1)
    point_B:tuple=(5*(index-1),8*(index-1)+1)
    print("d(A",index-1,",A",index,")=",round(euclidean_distance(point_A,point_B),2))
print("\n")    

############################################################################################

print("B)")

point_A6=(5*6,8*6+1)
point_A2=(5*2,8*2+1)
point_A8=(5*8,8*8+1)

matrix=np.zeros((3,3),dtype=int)

matrix[0][0]=point_A6[0]
matrix[0][1]=point_A6[1]
matrix[0][2]=1
matrix[1][0]=point_A2[0]
matrix[1][1]=point_A2[1]
matrix[1][2]=1
matrix[2][0]=point_A8[0]
matrix[2][1]=point_A8[1]
matrix[2][2]=1

print(matrix)
if(int(np.linalg.det(matrix))==0) :
    print("Punctele A6, A2 si A8 sunt coliniare.")
else : print("Punctele A6, A2 si A8 nu sunt coliniare.")
print("\n")

############################################################################################

print("C)")

point_A3=(5*3,8*3+1)
point_A4=(5*4,8*4+1)
point_A5=(5*5,8*5+1)

matrix_triangle=np.zeros((3,3),dtype=int)

matrix_triangle[0][0]=point_A3[0]
matrix_triangle[0][1]=point_A3[1]
matrix_triangle[0][2]=1
matrix_triangle[1][0]=point_A4[0]
matrix_triangle[1][1]=point_A4[1]
matrix_triangle[1][2]=1
matrix_triangle[2][0]=point_A5[0]
matrix_triangle[2][1]=point_A5[1]
matrix_triangle[2][2]=1

print(matrix_triangle)

print("Surface of triangle=",(np.linalg.det(matrix_triangle)/2))
if(int(np.linalg.det(matrix_triangle))/2 < 0) :
    print("Triunghiul este inversat.")

A)
d(A 0 ,A 1 )= 9.43
d(A 1 ,A 2 )= 9.43
d(A 2 ,A 3 )= 9.43
d(A 3 ,A 4 )= 9.43
d(A 4 ,A 5 )= 9.43


B)
[[30 49  1]
 [10 17  1]
 [40 65  1]]
Punctele A6, A2 si A8 sunt coliniare.


C)
[[15 25  1]
 [20 33  1]
 [25 41  1]]
Surface of triangle= 1.1046719095020293e-14


(1p) 3. Pentru o matrice de numere să se determine suma dintre cmmmdc si cmmmc al pătratelor sau cuburilor elementelor de pe linii sau de pe coloane, în funcție de valoarea unor parametri:
 + de tip boolean `compute_on_columns` 
 + de tip int `power` = 2 sau 3

In [87]:

def sum_hcm_or_lcm_matrix(matrix:np.matrix,compute_on_columns:bool, power:int)->int :
    """
    This function returns the sum of the highest common multiple and lowest common multiple of the perfect squares
    or cubes on a matrix line or collumn. 
    It takes 2 parameters, a bool which determines wether the values will be taken from a row or a collumn and an
    integer which determines whether the highest common multiple and lowest common multiple will be calculated
    from the perfect squares of the elements or the perfect cubes.
    It returns an integer.
    """
    power_matrix = matrix**power

    if compute_on_columns:
        highest_divisor = np.gcd.reduce(power_matrix, axis=0)
        lowest_multiple = np.lcm.reduce(power_matrix, axis=0)
        
    else:
        highest_divisor = np.gcd.reduce(power_matrix, axis=1)
        lowest_multiple = np.lcm.reduce(power_matrix, axis=1)
    return int(np.sum(highest_divisor) + np.sum(lowest_multiple))

            
test_matrix = np.array([[2, 4, 6],   # cmmdc = 4, cmmmc = 144 (rows)
                       [3, 9, 12],   # cmmdc = 9 , cmmmc = 1296 (rows)
                       [5, 25, 10]]) # cmmdc = 25, cmmc = 2500 (rows)
print(sum_hcm_or_lcm_matrix(test_matrix,False,2))

3978


(1p) 4. Pentru un număr introdus de la tastaură, generați o matrice pătratică cu elemente aleatorii din intervalul `[0,2n]`. Returnați un tuplu cu numerele formate din elementele de pe 
diagonala principală a matricei și cele de pe diagonala secundară a matricei. Verificați dacă acestea sunt palindroame.

In [88]:
def generate_matrix(number:int, size:int)->matrix :
    """
    This function generates a square matrix (with size given as input) with random elements in range (0,2*n), where n is an integer given as input.
    It returns a matrix.
    """
    return np.random.randint(low=0, high=2*number, size=(size,size), dtype=int) 

def matrix_diags(matrix:matrix)->tuple :
    """
    This function returns the elements situated on the diagonals of a square matrix.
    It returns a tuple.
    """
    principal_diag_elements=[matrix[i][i] for i in range (0,len(matrix))]
    secondary_diag_elements=[matrix[i][len(matrix)-i-1] for i in range (0,len(matrix))]
    return tuple(principal_diag_elements + secondary_diag_elements)  

def check_palindrom_tuple(elements:tuple)->bool :
    """
    This function checks if any element of the tuple is a palindrome.
    It returns a bool.
    The function called inside ("check_palindrom(element)") was defined at ex 3 in the first part of the homework.
    """
    for element in elements :
        if check_palindrom(element) == True :
            return True
    return False

n:int=input("Range=")
size:int=input("Size of matrix=")
matrix=generate_matrix(int(n),int(size))
print(matrix)
print(matrix_diags(matrix))
if check_palindrom_tuple(matrix_diags(matrix)) == True :
    print("Cel putin un element de pe una din diagonale este palindrom.")
else :  
    print("Niciun element de pe una din diagonale este palindrom.")

[[146 101 130  69 398]
 [  5  62 383 365 158]
 [396 249 265 214 324]
 [394 223  44 372 309]
 [149 126 117 395  32]]
(146, 62, 265, 372, 32, 398, 365, 265, 223, 149)
Niciun element de pe una din diagonale este palindrom.


(1.5p) 5. Descarcati setul de date Iris de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', si incarcati-l intr-o matrice NumPy, folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primind la intrare o matrice, returneaza un tuplu cu indicii de linii respectiv de coloane in care se gasesc valori NaN.

In [89]:
data = np.genfromtxt(r'C:\Users\ELITEBOOK\Documents\Facultate\AI\iris.txt', delimiter=',', dtype=None, usecols=(0, 1, 2, 3))

def generate_matrix_position()->tuple:
    """
    This function will generate a number position in the iris matrix, excluding the last collumn.
    It returns a tuple.
    """
    first_element:int=np.random.randint(0, 150)
    second_element:int=np.random.randint(0, 3)
    return (first_element,second_element)

def find_nan_values_matrix(matrix:matrix)->tuple :
    """
    This function will find the elements that are NaN in a matrix given as input.
    It returns a tuple containing the indexes of the elements with NaN value.
    """
    indexes = tuple((i,j) for i in range(len(matrix)) for j in range(len(matrix[0])) if np.isnan(matrix[i,j]))
    return indexes

for value in range(10) :
    position=generate_matrix_position()
    data[position[0],position[1]]=np.nan
print(data)
print(find_nan_values_matrix(data))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [nan 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 nan 0.5]
 [nan 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 nan 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  nan 0.3]
 [nan 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.